import 'package:get/get.dart';

class MyLocale implements Translations{
  @override
  Map<String, Map<String, String>> get keys => {
    'en' :{

      'hello' :'Hello!',
      'report' :'Report!',
      'pending' :'Pending',
      'ongoing' :'On-Going',
      'falsereport' : 'False-Report',
      'review' :'Review',
      'onbording1': 'Participate in the protection of the carriers service provider in your area',
      'onbording2' :'Participate in reducing infringements and violations contrived',
      'onbording3' : 'Receive special offers gifts in appreciation for your.',
      'save' : "Save",
      'mobile' : 'Mobile Nmuber',
      'pass' :'Password',
      'confpasss' :'Confirm Password',
      'loginmassage' :'By clicking Sign in, you agree to ',
      'loginmassagetext':'our Terms and Conditions and Privacy Policy',
      'verification' :'Verification',
      'verficationmassage' : 'We have sent you an SMS with a verification code on your number',
      'code':'Verification Code',
      'promassages' :'Thank you for reporting violations. To report directly, fill out the following form:',
      'promassage2' :'Briefly explain the situation',
      'procity' :'Neighborhood / District',
      'description' :'A description',
      'photo' :'Attach a photo',
      'send' : 'Send',
      'profile' :'Profile',
      'home' : 'Home',
      'report' : 'Reports',
      'confermproblem' :'Confirmation of the communication',
      'attachments' :'Attachments',
      'confirm' :'Confirm',
      'dalog':'The report has been created and will be reviewed. Thank you for your interest in the public interest',
      'gohome':'Go to the home page',
      'name':'Name',
      'address' :'Address',
      'email' :'Enail',
      'mobilenumber' :'Mobile Number',
      'reportdetails' : 'Report details',
      'reportmode' :'report mode',




      'login':'LogIn',
      'entermobile' :'Enter your Mobile Number' ,
      'enterpass' :'Enter your Password!',
      'entername' :'Enter your Name' ,
      'city' :'Select your city' ,
      'femeal' :'Femeal' ,
      'meal' :'Meal' ,
      'gender' :'Gender',
      'forgetpass' :'Forget Password',
      'contiune' :'Contiune',
      'donthave':'you have an account?',
      'welcom' :'Welcom!',
      'getstart' :'Get Start',
      'singup' :'Signin',
      'languges' :'Languges',
      'password' : 'Password',
      'haveaccount':"Alrady have an Account",
      '1' :'arabic' ,
      '2' :'enaglish',

      'lang': 'choose the language',


    },
    'ar' :{
      'lang' :'اختر  اللغة',
      'login':'تسجيل دخول',
      'welcom' :'اهلاً بك!',
      'getstart' :'هيا لنبدأ',
      'entername' :'ادخل اسمك' ,
      'city' :'اختار مدينتك' ,
      'femeal' :'انثى' ,
      'meal' :'ذكر' ,
      'gender' :'نوع الجنس',
      'haveaccount':"لدي بالفعل حساب",
      'entermobile' :'ادخل رقم الهاتف' ,
      'enterpass' :'ادخل كلمة المرور',
      'forgetpass' :'نسيت كلمة المرور',
      'contiune' :'استمر',
      'donthave':'لا امتلك حساب ',
      'singup' :'انشىء حساب',
      'languges' :'اللغة ',
      'password' : 'كلمة مرور',
      '1' :'عربية' ,
      '2' :'انجليزية',


      'hello' :'مرحبا!',
      'report' :'تقرير!',
      'pending' :'في انتظار المراجعة',
      'ongoing' :'مستمر',
      'falsereport' : 'بلاغ كاذب',
      'review' :'مراجعة',
      'onbording1': "المشاركة في حماية مزود خدمة الناقل في منطقتك",
      'onbording2' :"المشاركة في الحد من التعديات والانتهاكات المفتعلة",
      'onbording3' :  "تلقي هدايا العروض الخاصة تقديراً لك.",
      'save' : "حفظ",
      'mobile' : 'رقم الجوال',
      'pass' :'كلمة المرور',
      'confpasss' :'تأكيد كلمة المرور',
      'loginmassage' :'بالنقر فوق تسجيل الدخول ، فإنك توافق على',
      'loginmassagetext':'الشروط والأحكام وسياسة الخصوصية الخاصة بنا',
      'verification' :'التحقق',
      'verficationmassage' : 'لقد أرسلنا لك رسالة نصية قصيرة تحتوي على رمز التحقق على رقمك',
      'code':'التحقق من الرمز',
      'promassages' :'شكرًا على الإبلاغ عن الانتهاكات. للإبلاغ مباشرة ، املأ النموذج التالي:',
      'promassage2' : "اشرح الموقف بإيجاز",
      'procity' :'الحي /الشارع',
      'description' :'الوصف',
      'photo' :'التقاط صورة',
      'send' : 'ارسل',
      'profile' :'ملف شخصي',
      'home' : 'صفحة رئيسية',
      'report' : 'تقرير',
      'confermproblem' :'تأكيد الاتصال',
      'attachments' :'مرفقات',
      'confirm' :'موافق',
      'dalog':'تم إنشاء التقرير وستتم مراجعته. شكرا لك على اهتمامك بالمصلحة العامة',
      'gohome':'ارجع للصفحة الرئيسية',
      'name':'الاسم',
      'address' :'العنوان',
      'email' :'الايميل',
      'mobilenumber' :'رقم الجوال',
      'reportdetails' : 'تفاصيل التقرير',
      'reportmode' :'وضع التقرير',

    }

  };

}